/*
 * generated by Xtext 2.25.0
 */
package org.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ReqTxtStandaloneSetup extends ReqTxtStandaloneSetupGenerated {

	public static void doSetup() {
		new ReqTxtStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
