/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.ReqTxtRuntimeModule;
import org.xtext.ReqTxtStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ReqTxtIdeSetup extends ReqTxtStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ReqTxtRuntimeModule(), new ReqTxtIdeModule()));
	}
	
}
