/**
 * generated by Xtext 2.25.0
 */
package org.xtext.reqTxt;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.reqTxt.ReqTxtFactory
 * @model kind="package"
 * @generated
 */
public interface ReqTxtPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "reqTxt";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/ReqTxt";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "reqTxt";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReqTxtPackage eINSTANCE = org.xtext.reqTxt.impl.ReqTxtPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.reqTxt.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.reqTxt.impl.ModelImpl
   * @see org.xtext.reqTxt.impl.ReqTxtPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Reqs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__REQS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.reqTxt.impl.ReqDesImpl <em>Req Des</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.reqTxt.impl.ReqDesImpl
   * @see org.xtext.reqTxt.impl.ReqTxtPackageImpl#getReqDes()
   * @generated
   */
  int REQ_DES = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQ_DES__NAME = 0;

  /**
   * The number of structural features of the '<em>Req Des</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQ_DES_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.reqTxt.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.reqTxt.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.reqTxt.Model#getReqs <em>Reqs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Reqs</em>'.
   * @see org.xtext.reqTxt.Model#getReqs()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Reqs();

  /**
   * Returns the meta object for class '{@link org.xtext.reqTxt.ReqDes <em>Req Des</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Req Des</em>'.
   * @see org.xtext.reqTxt.ReqDes
   * @generated
   */
  EClass getReqDes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.reqTxt.ReqDes#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.reqTxt.ReqDes#getName()
   * @see #getReqDes()
   * @generated
   */
  EAttribute getReqDes_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ReqTxtFactory getReqTxtFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.reqTxt.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.reqTxt.impl.ModelImpl
     * @see org.xtext.reqTxt.impl.ReqTxtPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Reqs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__REQS = eINSTANCE.getModel_Reqs();

    /**
     * The meta object literal for the '{@link org.xtext.reqTxt.impl.ReqDesImpl <em>Req Des</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.reqTxt.impl.ReqDesImpl
     * @see org.xtext.reqTxt.impl.ReqTxtPackageImpl#getReqDes()
     * @generated
     */
    EClass REQ_DES = eINSTANCE.getReqDes();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REQ_DES__NAME = eINSTANCE.getReqDes_Name();

  }

} //ReqTxtPackage
