/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.reqTxt.ui.internal.ReqTxtActivator;

public class ReqTxtUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ReqTxtActivator.getInstance().getInjector("org.xtext.ReqTxt");
	}

}
