/*
 * generated by Xtext 2.25.0
 */
package org.xtext.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.reqTxt.ReqDes;
import org.eclipse.xtext.util.Strings;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ReqTxtValidator extends AbstractReqTxtValidator {
	@Check
	public void checkCondition(ReqDes des) {
		String con = des.getName();
		//触发事件缺失
		if(Strings.isEmpty(con)) {
			warning("Maybe you have forgotten to write the trigger?", null);
		}
		//while模板对于其他状态的处理
		else if (con.charAt(0)=='W' && con.charAt(2)=='i') {
			warning("Have you considered other states?",null);
		}
		else if (con.charAt(0) == 'I') {
			warning("What if the situation doesn't happen?",null);
		}
	}
}
