# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Requirement.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Requirement.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\013Beihang.NLP',
  serialized_pb=b'\n\x11Requirement.proto\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\t\"*\n\ttwoValues\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06value1\x18\x02 \x01(\t\"<\n\x0bthreeValues\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06value1\x18\x02 \x01(\t\x12\x0e\n\x06value2\x18\x03 \x01(\t2\xe0\x03\n\x0bRequirement\x12$\n\x08Itemized\x12\n.twoValues\x1a\n.twoValues\"\x00\x12.\n\x0eRelate_Re_Sugg\x12\x0c.threeValues\x1a\x0c.threeValues\"\x00\x12\"\n\x0erechangeimpact\x12\x06.Value\x1a\x06.Value\"\x00\x12#\n\x0fstructurization\x12\x06.Value\x1a\x06.Value\"\x00\x12\"\n\x0e\x63onflictdetect\x12\x06.Value\x1a\x06.Value\"\x00\x12 \n\x0crelationship\x12\x06.Value\x1a\x06.Value\"\x00\x12\x1e\n\nchecksplit\x12\x06.Value\x1a\x06.Value\"\x00\x12$\n\x10\x63lassifySecurity\x12\x06.Value\x1a\x06.Value\"\x00\x12!\n\rRelate_FR_NFR\x12\x06.Value\x1a\x06.Value\"\x00\x12%\n\x0boriginTrace\x12\x0c.threeValues\x1a\x06.Value\"\x00\x12 \n\x06mTrace\x12\x0c.threeValues\x1a\x06.Value\"\x00\x12\x1c\n\x08taskcost\x12\x06.Value\x1a\x06.Value\"\x00\x12\x1c\n\x08gen_anal\x12\x06.Value\x1a\x06.Value\"\x00\x42\r\n\x0b\x42\x65ihang.NLPb\x06proto3'
)




_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Value.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=43,
)


_TWOVALUES = _descriptor.Descriptor(
  name='twoValues',
  full_name='twoValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='twoValues.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value1', full_name='twoValues.value1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=87,
)


_THREEVALUES = _descriptor.Descriptor(
  name='threeValues',
  full_name='threeValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='threeValues.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value1', full_name='threeValues.value1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value2', full_name='threeValues.value2', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['twoValues'] = _TWOVALUES
DESCRIPTOR.message_types_by_name['threeValues'] = _THREEVALUES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'Requirement_pb2'
  # @@protoc_insertion_point(class_scope:Value)
  })
_sym_db.RegisterMessage(Value)

twoValues = _reflection.GeneratedProtocolMessageType('twoValues', (_message.Message,), {
  'DESCRIPTOR' : _TWOVALUES,
  '__module__' : 'Requirement_pb2'
  # @@protoc_insertion_point(class_scope:twoValues)
  })
_sym_db.RegisterMessage(twoValues)

threeValues = _reflection.GeneratedProtocolMessageType('threeValues', (_message.Message,), {
  'DESCRIPTOR' : _THREEVALUES,
  '__module__' : 'Requirement_pb2'
  # @@protoc_insertion_point(class_scope:threeValues)
  })
_sym_db.RegisterMessage(threeValues)


DESCRIPTOR._options = None

_REQUIREMENT = _descriptor.ServiceDescriptor(
  name='Requirement',
  full_name='Requirement',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=152,
  serialized_end=632,
  methods=[
  _descriptor.MethodDescriptor(
    name='Itemized',
    full_name='Requirement.Itemized',
    index=0,
    containing_service=None,
    input_type=_TWOVALUES,
    output_type=_TWOVALUES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Relate_Re_Sugg',
    full_name='Requirement.Relate_Re_Sugg',
    index=1,
    containing_service=None,
    input_type=_THREEVALUES,
    output_type=_THREEVALUES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rechangeimpact',
    full_name='Requirement.rechangeimpact',
    index=2,
    containing_service=None,
    input_type=_VALUE,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='structurization',
    full_name='Requirement.structurization',
    index=3,
    containing_service=None,
    input_type=_VALUE,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='conflictdetect',
    full_name='Requirement.conflictdetect',
    index=4,
    containing_service=None,
    input_type=_VALUE,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='relationship',
    full_name='Requirement.relationship',
    index=5,
    containing_service=None,
    input_type=_VALUE,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='checksplit',
    full_name='Requirement.checksplit',
    index=6,
    containing_service=None,
    input_type=_VALUE,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='classifySecurity',
    full_name='Requirement.classifySecurity',
    index=7,
    containing_service=None,
    input_type=_VALUE,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Relate_FR_NFR',
    full_name='Requirement.Relate_FR_NFR',
    index=8,
    containing_service=None,
    input_type=_VALUE,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='originTrace',
    full_name='Requirement.originTrace',
    index=9,
    containing_service=None,
    input_type=_THREEVALUES,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='mTrace',
    full_name='Requirement.mTrace',
    index=10,
    containing_service=None,
    input_type=_THREEVALUES,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='taskcost',
    full_name='Requirement.taskcost',
    index=11,
    containing_service=None,
    input_type=_VALUE,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='gen_anal',
    full_name='Requirement.gen_anal',
    index=12,
    containing_service=None,
    input_type=_VALUE,
    output_type=_VALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REQUIREMENT)

DESCRIPTOR.services_by_name['Requirement'] = _REQUIREMENT

# @@protoc_insertion_point(module_scope)
