/*
 * generated by Xtext 2.25.0
 */
package org.xtext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.reqTxt.Model;
import org.xtext.reqTxt.ReqDes;
import org.xtext.reqTxt.ReqTxtPackage;
import org.xtext.services.ReqTxtGrammarAccess;

@SuppressWarnings("all")
public class ReqTxtSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ReqTxtGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ReqTxtPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ReqTxtPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case ReqTxtPackage.REQ_DES:
				sequence_ReqDes(context, (ReqDes) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     reqs+=ReqDes+
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ReqDes returns ReqDes
	 *
	 * Constraint:
	 *     name=Condition
	 */
	protected void sequence_ReqDes(ISerializationContext context, ReqDes semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ReqTxtPackage.Literals.REQ_DES__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ReqTxtPackage.Literals.REQ_DES__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getReqDesAccess().getNameConditionParserRuleCall_0_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
}
