/*
 * generated by Xtext 2.25.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalReqTxtParser;
import org.xtext.services.ReqTxtGrammarAccess;

public class ReqTxtParser extends AbstractAntlrParser {

	@Inject
	private ReqTxtGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalReqTxtParser createParser(XtextTokenStream stream) {
		return new InternalReqTxtParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ReqTxtGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ReqTxtGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
